import type { FieldSpec, Fields, Resource, SiteSpec } from '@daddyapi/spec';

type JsonSchema = Record<string, unknown>;

function scalarType(spec: FieldSpec): string {
  if (typeof spec === 'string') return 'string';
  const transforms = spec.transform
    ? Array.isArray(spec.transform)
      ? spec.transform
      : [spec.transform]
    : [];
  if (transforms.some((t) => t === 'int' || t === 'float' || t === 'number')) return 'number';
  if (transforms.includes('boolean')) return 'boolean';
  return 'string';
}

function fieldSchema(spec: FieldSpec): JsonSchema {
  const scalar: JsonSchema = { type: scalarType(spec) };
  if (typeof spec !== 'string' && spec.many) return { type: 'array', items: scalar };
  return scalar;
}

function itemSchema(fields: Fields): JsonSchema {
  const properties: Record<string, JsonSchema> = {};
  for (const [name, spec] of Object.entries(fields)) properties[name] = fieldSchema(spec);
  return { type: 'object', properties };
}

function resourceDataSchema(resource: Resource): JsonSchema {
  if (resource.list) return { type: 'array', items: itemSchema(resource.list.fields) };
  return itemSchema(resource.item!.fields);
}

function templateParams(path: string): string[] {
  const params: string[] = [];
  for (const match of path.matchAll(/\{(\w+)\}/g)) params.push(match[1]!);
  return params;
}

/** Generate an OpenAPI 3 document from a SiteSpec. */
export function buildOpenApi(spec: SiteSpec): JsonSchema {
  const paths: Record<string, unknown> = {};

  for (const resource of spec.resources) {
    const parameters: JsonSchema[] = [];
    for (const param of templateParams(resource.fetch.path)) {
      parameters.push({ name: param, in: 'query', required: true, schema: { type: 'string' } });
    }
    if (resource.list && resource.fetch.pagination) {
      parameters.push({
        name: 'pages',
        in: 'query',
        required: false,
        description: 'Maximum number of pages to fetch.',
        schema: { type: 'integer', minimum: 1 },
      });
    }

    paths[`/${resource.name}`] = {
      get: {
        summary: resource.description ?? `Fetch ${resource.name}`,
        parameters,
        responses: {
          '200': {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    data: resourceDataSchema(resource),
                    warnings: { type: 'array', items: { type: 'object' } },
                    meta: { type: 'object' },
                  },
                },
              },
            },
          },
        },
      },
    };
  }

  return {
    openapi: '3.0.3',
    info: {
      title: `${spec.name} API`,
      version: '0.1.0',
      description: spec.description ?? `Auto-generated by daddyapi from ${spec.baseUrl}`,
    },
    servers: [{ url: '/' }],
    paths,
  };
}
